services: 
  app:
    build: ./service/
    ports:
      - 6969:6969
    environment:
      NATS_URL: "nats"
      DB_URL: "postgres"
    depends_on:
      - nats
      - postgres
  nats:
    image: nats
    ports: 
      - 8222:8222
      - 4222:4222
    command:
      - "-js"
    volumes:
      - nats-data:/tmp/nats
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "order_service"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
      - 5050:5050
    depends_on:
      - postgres


volumes:
  pg-data:
  pgadmin:
  nats-data:
